### ISSUE TITLE
Fix top and bottom margin for logo in the nav bar

### ISSUE THREAD

**Issue by notthetup** [subnero1/website#10]
_From @sayanee on September 9, 2018 9:33_

![image](https://user-images.githubusercontent.com/413879/45263124-646f4100-b456-11e8-83a5-4783e7633b52.png)

❌  No bottom margin!

✅ Should have equal top and bottom margin

_Copied from original issue: notthetup/website#1_

**Comment by manuignatius** [comment]
Done.

**Comment by AnneThKu** [comment]
Added margin-bottom :10 px for the image
