### ISSUE TITLE
Make paragraph font size bigger

### ISSUE THREAD

**Issue by notthetup** [subnero1/website#12]
_From @sayanee on September 9, 2018 9:46_

## Before

![image](https://user-images.githubusercontent.com/413879/45263239-33900b80-b458-11e8-9d21-806aae3e2b8f.png)

## After

![image](https://user-images.githubusercontent.com/413879/45263277-de082e80-b458-11e8-8f3c-72da873a14e1.png)

```
p {
    font-size: 2rem;
}
```

❌ `165` characters per line 😭 
✅ Characters per line should be less than `80`

_Copied from original issue: notthetup/website#3_

**Comment by manuignatius** [comment]
Done.
